### ISSUE TITLE
Can the source code for the package be provided?

### ISSUE THREAD

**Issue by Sunday2020** [scwatson812/COVID19WastewaterModel#2]
Can the source code for the package be provided, and I would like to reproduce your article from the lancet, which shows a version too low to use after installed, thank you !

**Comment by scwatson812** [comment]
Hello,

Thank you for the message.  The package does not seem to be compatible with the latest version of R.  The source code has been added to Github (Source_Code) file. This code implements all the functions in the R package.

Best,

Stella Self

From: Sunday2020 ***@***.***>
Sent: Sunday, December 26, 2021 5:45 AM
To: scwatson812/COVID19WastewaterModel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [scwatson812/COVID19WastewaterModel] Can the source code for the package be provided? (Issue #2)


Can the source code for the package be provided, and I would like to reproduce your article from the lancet, which shows a version too low to use after installed, thank you !

—
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-31327df5-454455534531-3fcdc6feff3c2cc3&q=1&e=96c2a8ac-a8b4-407e-925e-4764e22e2d68&u=https%3A%2F%2Fgithub.com%2Fscwatson812%2FCOVID19WastewaterModel%2Fissues%2F2>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-31327df5-454455534531-53b3934b713a61d6&q=1&e=96c2a8ac-a8b4-407e-925e-4764e22e2d68&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO4ABMSKHRLRMSJDOLU5PVTUS3W25ANCNFSM5KYY5XFA>.
Triage notifications on the go with GitHub Mobile for iOS<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-31327df5-454455534531-7045840aacf1c8ac&q=1&e=96c2a8ac-a8b4-407e-925e-4764e22e2d68&u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-31327df5-454455534531-ddc2c2d26099be72&q=1&e=96c2a8ac-a8b4-407e-925e-4764e22e2d68&u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

**Comment by Sunday2020** [comment]
Thank you , Stella.

 I have seen  attachments here,  the script containing much of the analysis code I had hoped for.

I'll close this issue now!

All the best,
John
